// export const Type = {
//   FETCH_POSTS: 'FETCH_POSTS',
//   DELETE_ITEMS: 'DELETE_ITEMS',
//   FIND_POSTS: 'FIND_POSTS',
// };

export const Type = {
  FETCH_POSTS_START: 'FETCH_POSTS_START',
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
  FETCH_POSTS_ERROR: 'FETCH_POSTS_ERROR',

  DELETE_POSTS_START: 'DELETE_POSTS_START',
  DELETE_POSTS_SUCCESS: 'DELETE_POSTS_SUCCESS',
  DELETE_POSTS_ERROR: 'DELETE_POSTS_ERROR',

  ADD_POSTS_START: 'ADD_POSTS_START',
  ADD_POSTS_SUCCESS: 'ADD_POSTS_SUCCESS',
  ADD_POSTS_ERROR: 'ADD_POSTS_ERROR',

  DELETE_ITEMS: 'DELETE_ITEMS',
  FIND_POSTS: 'FIND_POSTS',
};
