const Type = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  CHANGE_VALUE: "CHANGE_VALUE",
  GET_POSTS: "GET_POSTS",
  SELECT_VALUE: "SELECT_VALUE",
  DELETE_ITEMS: "DELETE_ITEMS"
};

export default Type;
